### ISSUE TITLE
Implement the normal gravity potential of the Ellipsoid

### ISSUE THREAD

**Issue by leouieda** [fatiando/boule#151]
**Description of the desired feature:**

If we want to calculate the disturbing potential for geophysical studies, we need a way to calculate the normal gravity and gravitational potentials. Tools like [ICGEM](http://icgem.gfz-potsdam.de/calcgrid) can provide grids of the gravitational potential.

Equation 2–124 in Hofmann-Wellenhof & Moritz (2006) is the normal gravitational potential in ellipsoidal harmonic coordinates. The centrifugal term is not hard and can be found earlier in the same book. The challenge is converting the geodetic to ellipsoidal harmonic coordinates. The conversion can be found in [Lakshmanan (1991)](https://doi.org/10.1190/1.1443090). The final equation can be obtained by substitution.

The idea is to add 3 new methods to `Ellipsoid`:

1. `centrifugal_potential(self, latitude, height)`: Calculate the centrifugal potential.
2. `normal_gravitational_potential(self, latitude, height)`: Calculate the gravitational potential using the equations described above.
3. `normal_gravity_potential(self, latitude, height)`: Returns the sum of the previous 2. 

**Are you willing to help implement and maintain this feature?** 

Yes but it will take some time. Having some help would be much appreciated!

**Comment by MarkWieczorek** [comment]
I think that these three functions would be very useful to have. However, what I really need for my work is simply the normal gravity potential on the surface of the ellipsoid ($U_0$), which is independent of latitude. This is simply equation 2-123 in the same book.

$U_0$ could be computed as  `normal_gravity_potential(latitude=arbitrary_value, height=0)`, but  this would be somewhat awkward if either latitude or height were required arguments. If they were both optional, we could compute it as `normal_gravity_potential()`. Perhaps a better way for my interests would be to implement $U_0$ as a property, but then we would need to come up with a unique name that is distinct from the more general function. We could call it `U0`, but this would go against the verbose naming scheme we are using.

**Comment by MarkWieczorek** [comment]
For the normal gravity potential on the ellipsoid, $U_0$: 

I think that we could make this an attribute that is simply called `reference_potential`. To obtain the potential above the ellipsoid (which depends on latitude), one would then use the more general functions discussed above.
