### ISSUE TITLE
Comments regarding the InSight lander coordinates example

### ISSUE THREAD

**Issue by MarkWieczorek** [fatiando/boule#166]
In the "Coordinate conversion" section of the documentation, there is an example of some simple coordinate transformations that make use of the InSight lander coordinates. However, the documentation assumes that the coordinates are geodetic with respect to an ellipsoid, when they are in fact planetocentric with respect to the geoid. The cited LPSC abstract states the following:

> On Nov. 26, 2018 at 11:52:59 a.m. PST, the InSight lander touched down on Mars at 4.502384°N, 135.623447°E (planetocentric, IAU 2000) with an elevation of -2613.426 m with respect to the Mars Orbiter Laser Altimeter (MOLA) geoid.

This is a bit messy, because the geoid is somewhat arbitrary, and the "MOLA geoid" is just some file on the PDS...

I suggest that we instead demonstrate the coordinate conversions using the Cartesian (x, y, z) coordinates of the RISE experiment that is on the lander from 
> Le Maistre, S., Rivoldini, A., Caldiero, A., Yseboodt, M., Baland, R.-M., Beuthe, M., Van Hoolst, T., Dehant, V., Folkner, W. M., Buccino, D., Kahan, D., Marty, J.-C., Antonangeli, D., Badro, J., Drilleau, M., Konopliv, A., Péters, M.-J., Plesa, A.-C., Samuel, H., … Banerdt, W. B. (2023). Spin state and deep interior structure of Mars from InSight radio tracking. Nature, 1–5. https://doi.org/10.1038/s41586-023-06150-0

If you look in the Supplement Table S1, you will see that there are coordinates for each of the two antennas, as well as using two different methods. I propose (arbitrarily) to just take the GINS solution for the entire mission for the "west" antenna. The coordinates are:

`[-2417504.5, 2365954.5, 266266.7]`

From these, we could demonstrate how to compute both the planetocentric and geodetic coordinates.

**Comment by leouieda** [comment]
Good catch! I like the suggestion as well. Thanks!
