### ISSUE TITLE
Tutorial about coordinate conversions

### ISSUE THREAD

**Issue by leouieda** [fatiando/boule#20]
We need a tutorial page explaining the differences between geodetic and geocentric coordinates and how to convert between them using Boule. Tutorials are rendered by sphinx-gallery from python scripts in `tutorials/`. See the existing ones for the format.

**Comment by LL-Geo** [comment]
I draft a tutorial about the coordinates.  Is that make sense? https://github.com/fatiando/boule/pull/84

**Comment by leouieda** [comment]
@LL-Geo so sorry for the long delay in this! Really haven't had the bandwidth for Boule lately but I'm trying to set aside some time to work on this again. Thanks for helping out!
