### ISSUE TITLE
Convert geocentric geodetic coordinates into geocentric Cartesian coordinates 

### ISSUE THREAD

**Issue by birocoles** [fatiando/boule#29]
Currently, harmonica has functions for converting geocentric geodetic to geocentric spherical coordinates and vice versa. It would be useful to include a functions for converting geocentric Cartesian to geocentric geodetic coordinates. These functions would use the reference ellipsoids defined by boule.

**Comment by leouieda** [comment]
@birocoles this would be great to have here :+1: It should be a method in `boule.Ellipsoid`.

To clarify, do you mean geocentric *spherical* to Cartesian? The geodetic coordinates aren't really geocentric, right?

Either way, the method should look similar to the current `geodetic_to_spherical` (and its inverse).

**Comment by birocoles** [comment]
Hi @leouieda ,

There is a vast and complicated literature about coordinate systems used in geodesy (e.g., Soler, 1976; Soler & Hothem, 1988; Jekeli, 2012). I think we need to define a common nomenclature here. 

Geodetic coordinates are defined by using a reference ellipsoid. Some ellipsoids are geocentric (e.g., NAD83, WGS84) and some ellipsoids are non-geocentric (e.g., NAD27). 

The common formulas for transforming geodetic coordinates into geocentric Cartesian coordinates presume that the origin of the Cartesian system coincides with the center of the reference ellipsoid (Jekeli, 2012, subsection 2.1.5). 

I will try to put all these together to make things as clear as possible in Boule.

Soler, T. (1976). On differential transformations between Cartesian and curvilinear (geodetic) coordinates, Depart. of Geodetic Science, Report no. 236. The Ohio State University, Columbus, Ohio. url: https://www.ngs.noaa.gov/web/data_imagery/CORS/Articles/

Soler, T. & L.D. Hothem (1988). Coordinate systems used in geodesy: Basic definitions and concepts, J. Surv. Eng., ASCE, 114(2), 84-97. url: https://www.ngs.noaa.gov/web/data_imagery/CORS/Articles/

Jekeli, C. (2012). Geometric Reference Systems in Geodesy, The Ohio State University. url: http://hdl.handle.net/1811/51274

**Comment by leouieda** [comment]
@birocoles you’re right and we have to be careful with the wording of things. We can probably focus only on the geocentric ellipsoids for now. To avoid confusion it might be best to leave the word "geocentric" for the spherical coordinates. Then we can discriminate the elipsoids that are non-geocentric since they will be an exception.

**Comment by leouieda** [comment]
@birocoles have a look at this discussion geospace-code/pymap3d#24 This package might already have what we need.

**Comment by leouieda** [comment]
Closing since this is available in `pymap3d.geodetic2ecef` and its inverse. As of #121 we can pass Boule ellipsoids to pymap3d functions so there is no need to re-implement this here.
