### ISSUE TITLE
Point to Harmonica's Gravity Disturbances gallery example on Normal Gravity

### ISSUE THREAD

**Issue by santisoler** [fatiando/boule#31]
**Description of the desired feature**

On the Normal Gravity gallery example, would be nice to point towards the [Harmonica's Gravity Disturbances](https://www.fatiando.org/harmonica/latest/gallery/gravity_disturbance.html) gallery example, just to show how the `normal_gravity` method could be applied to the computation of the gravity disturbances.

The lack of clearness on how `normal_gravity` should be used was raised by @craigmillernz on fatiando/harmonica#164.

**Are you willing to help implement and maintain this feature?** Yes

**Comment by santisoler** [comment]
As discussed in last meeting, I agree with moving the gravity disturbance tutorial to Boule. It also sounded weird that the first two pages of Harmonica User Guide don't use Harmonica at all. And the same goes for the coordinates systems: since it's something we use across the Fatiando libraries, it should be placed in a different place than Harmonica's docs.

**Comment by leouieda** [comment]
Closing this since there is a tutorial here already.
