### ISSUE TITLE
Provide function that returns the radius as a function of latitude

### ISSUE THREAD

**Issue by MarkWieczorek** [fatiando/boule#34]
It would be very useful to be able to compute the radius of the reference ellipsoid as a function of latitude (geocentric or geodetic). 

The use case I am thinking of is the following. Most spherical harmonic models of planetary topography provide the absolute radius of the surface. In many cases, it makes more sense to remove either a reference ellipse (which could be a sphere), or to remove the geoid. In pyshtools, I would like to create a grid of the radius of the reference ellipsoid like `grid = pysh.SHGrid.from_ellipsoid()`, and for this it would be most easy to input a boule ellipsoid and to use a boule function to compute the radius as function of latitude.

**Comment by leouieda** [comment]
@MarkWieczorek do you know if there is a smarter way of doing this than geodetic -> ECEF (cartesian) -> radius?

**Comment by leouieda** [comment]
Nevermind, found this: https://en.wikipedia.org/wiki/Earth_radius#Geocentric_radius

**Comment by MarkWieczorek** [comment]
I probably would have done the less smart option....
