### ISSUE TITLE
Check if normal gravity is computed on internal point

### ISSUE THREAD

**Issue by santisoler** [fatiando/boule#44]
**Description of the desired feature**

The normal gravity formulas used on `boule.Ellipsoid.normal_gravity()` and `boule.Sphere.normal_gravity()` are valid only for points outside the ellipsoid.
Would be nice to add a warning in case the given point falls inside it.
To do so we just need to check if the `height` is positive or equal to zero.

**Are you willing to help implement and maintain this feature?** Yes, but would be glad to help anyone who wants to implement it.

**Comment by MGomezN** [comment]
Hello! I want to implement it! :P

**Comment by santisoler** [comment]
Awesome @MGomezN! I'm glad to have you onboard!

You start by reading the [Contributing Guidelines](https://github.com/fatiando/boule/blob/master/CONTRIBUTING.md) so you can set up your environment and have a clear image of how the whole process of contributing looks like.

Feel free to open a Pull Request whenever you are ready. Remember that you can open a PR at any stage, so the code doesn't have to be completely finished to do so. You can upload a draft if you need any help and want us to see the code.

And don't hesitate to ask for help if you need it!
