### ISSUE TITLE
Add reference ellipsoids for the Moon, Venus and Mercury

### ISSUE THREAD

**Issue by santisoler** [fatiando/boule#53]
**Description of the desired feature**

With the new `Sphere` class introduced in #42 for representing reference ellipsoids with zero flattening, now we are in position to add ellipsoids for planetary bodies that are usually treated as spheres, such as the Moon, Venus and Mercury.

@leouieda started adding the reference ellipsoid for the Moon on #13 before we had the `Sphere` class for that purpose, encountering the known problems of singularities due to division by zero (see #18).

The idea is to add new `MOON`, `VENUS` and `MERCURY` instances of the `Sphere` class with the correct parameters for the each body (they can be taken from [Wieczorek (2015)](https://doi.org/10.1016/B978-0-444-53802-4.00169-X)). These three variables should be defined in the [`boule/realizations.py` file](https://github.com/fatiando/boule/blob/master/boule/realizations.py).

**Are you willing to help implement and maintain this feature?**
Yes, I'm willing to help anyone that wants to implement it (yes, I'm talking to you)! :rocket:

If you want to add just one of these bodies, it's ok: we can add each one of them on separated PRs.

**Comment by dabiged** [comment]
Hi All, first time contributor to boule. 
I have had a go at adding VENUS. I am not sure about the syntax exactly in the declaration (sphere vs spheroid) or the doctest (should I test for semi-major axis and/or radius).

I am happy to take directions from more senior maintainers.

**Comment by leouieda** [comment]
@dabiged thanks for the PR 🙂 For `Sphere`, you could use either `radius` or `semimajor_axis` since it sets them both to the same value. Otherwise, all looks on and PR is merged (there was a slight mistake in the radius with a trailing 0 that shouldn't be there).

**Comment by santisoler** [comment]
Hi @dabiged! Glad to have you onboard! :rocket: 
Thank you very much for volunteering to contribute.

> I have had a go at adding VENUS. I am not sure about the syntax exactly in the declaration (sphere vs spheroid)

So, you would need to add a new `VENUS` variable to [`realizations.py`](https://github.com/fatiando/boule/blob/master/boule/realizations.py), like `WGS84` or `MARS` are defined. The main differences is that instead of using the [`Ellipsoid`](https://github.com/fatiando/boule/blob/0ecbb669596c67c3856384ad8b8148337fec23d3/boule/ellipsoid.py#L12) class, we will use the [`Sphere`](https://github.com/fatiando/boule/blob/0ecbb669596c67c3856384ad8b8148337fec23d3/boule/sphere.py#L15) class, which is actually a child of `Ellipsoid`.

The `Ellipsoid` class represents ellipsoids of revolution, a.k.a spheroids or bi-axial ellipsoids, while the `Sphere` class represents actual spheres (constant radius). There is an open Issue (https://github.com/fatiando/boule/issues/47) for adding a class tri-axial ellipsoids, but that's out of the scope of this Issue.

> or the doctest (should I test for semi-major axis and/or radius).

I don't think you would need to add any further tests. Once you add `VENUS` to the `ELLIPSOIDS` list, every test on https://github.com/fatiando/boule/blob/master/boule/tests/test_ellipsoid.py will also be carried out on the new `VENUS` one.
And FIY, you should use the `radius` argument to define `VENUS` rather than the `semimajor_axis`.

Feel free to open a PR whenever you're ready! And don't hesitate to ask for help if you need it.

**Comment by santisoler** [comment]
Haha that PR moved really fast!

**Comment by leouieda** [comment]
That's what happens when I have 30 minutes to spare and don't want to open my emails 😉
